/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cn_horizon_life_ndk_NDkTest */

#ifndef _Included_com_cn_horizon_life_ndk_NDkTest
#define _Included_com_cn_horizon_life_ndk_NDkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cn_horizon_life_ndk_NDkTest
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cn_horizon_life_ndk_NDkTest_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
